# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.950'
    hooks:
    -   id: mypy
        args: [--no-strict-optional, --ignore-missing-imports]
-   repo: https://github.com/psf/black
    rev: '22.3.0'
    hooks:
    -   id: black
